name: Build & publish haiku.rag to pypi
on:
  workflow_run:
    workflows: ["Build & publish haiku.rag-slim to pypi"]
    types:
      - completed
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event_name == 'workflow_dispatch' || github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v4
      - name: Set up uv
        run: curl -LsSf https://astral.sh/uv/0.3.0/install.sh | sh
      - name: Set up Python 3.12
        run: uv python install 3.12
      - name: Build haiku.rag
        run: uv build
      - name: Publish haiku.rag
        run: uvx twine upload -u __token__ -p ${{ secrets.PYPI_API_TOKEN }} dist/* --non-interactive
